# config.py

# Energy and health
MAX_ENERGY = 200
ENERGY_ADD = 1
MAX_HEALTH = 100
HEALTH_ADD = 2
STARTER_ENERGY = 100
STARTER_HEALTH = 100
REPRODUCTION_ENERGY_COST = 60
REPRODUCTION_MIN_ENERGY = 120
REPRODUCTION_ANIMAL_MAX_AGE = 30
REPRODUCTION_PLANT_MAX_AGE = 120
DEFAULT_COST_OF_LIVING = 1
MIN_ENERGY_TO_SEEK_FOOD = 120
COMFORT_ENERGY_LEVEL = 160
CRITICAL_ENERGY_LEVEL = 20

# Movement
SPRINT_SPEED_MULTIPLIER = 2
SPRINT_ENERGY_MULTIPLIER = 2
BASE_MOVE_COST = 1
MIN_DISTANCE_TO_EAT = 2.0
FLEE_DISTANCE_THRESHOLD = 8.0
# Metabolism and growth
PLANT_GROWTH_MULTIPLIER = 0.6
PLANT_ENERGY_REWARD = 20
PLANT_REPRODUCTION_SIZE = 3.0
PLANT_MAX_POPULATION = 20
# Probabilities
SOUND_PRODUCTION_CHANCE = 0.1
REPRODUCTION_ANIMAL_CHANCE = 0.7
