# config.py

# Energy and health
MAX_ENERGY = 200
STARTER_ENERGY = 100
REPRODUCTION_ENERGY_COST = 100
REPRODUCTION_MIN_ENERGY = 150

# Movement
SPRINT_SPEED_MULTIPLIER = 2
SPRINT_ENERGY_MULTIPLIER = 3
BASE_MOVE_COST = 1

# Metabolism and growth
PLANT_GROWTH_MULTIPLIER = 0.5
PLANT_ENERGY_REWARD = 10
