# config.py
# TODO: пофиксить баланс выдачи энергии в симуляции
# Energy and health
MAX_ENERGY = 200
ENERGY_ADD = 3
MAX_HEALTH = 100
HEALTH_ADD = 2
STARTER_ENERGY = 100
STARTER_HEALTH = 100
REPRODUCTION_ENERGY_COST = 100
REPRODUCTION_MIN_ENERGY = 150
DEFAULT_COST_OF_LIVING = 2
MIN_ENERGY_TO_SEEK_FOOD = 70
COMFORT_ENERGY_LEVEL = 90
# Movement
SPRINT_SPEED_MULTIPLIER = 2
SPRINT_ENERGY_MULTIPLIER = 3
BASE_MOVE_COST = 1

# Metabolism and growth
PLANT_GROWTH_MULTIPLIER = 0.5
PLANT_ENERGY_REWARD = 10

# Probabilities
SOUND_PRODUCTION_CHANCE = 0.1
